version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - print env
  pre_build:
    commands:
      - echo Starting build...
  build:
    commands:
      - echo Building the React app...
      - npm run build # This generates the build directory with static files
  post_build:
    commands:
      - echo Copying files to S3...
      - aws s3 sync build/ s3://$BUCKET_NAME --delete
      - echo Build completed successfully.
artifacts:
  files:
    - "**/*" # Include all files in the build directory
  base-directory: build # Set the base directory to the build folder
